server:
  port: 8081
  servlet:
    context-path: /profile

  spring:
    profiles:
      active: test
    data:
      neo4j:
        uri: bolt://localhost:7687
        username: neo4j
        password: 12345678
